//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominionCardGame.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DominionCardGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _372px_Copper {
            get {
                object obj = ResourceManager.GetObject("_372px_Copper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _372px_Curse {
            get {
                object obj = ResourceManager.GetObject("_372px_Curse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _372px_Duchy {
            get {
                object obj = ResourceManager.GetObject("_372px_Duchy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _372px_Moat {
            get {
                object obj = ResourceManager.GetObject("_372px_Moat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _373px_Collection {
            get {
                object obj = ResourceManager.GetObject("_373px_Collection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _373px_Estate {
            get {
                object obj = ResourceManager.GetObject("_373px_Estate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _373px_Smithy {
            get {
                object obj = ResourceManager.GetObject("_373px_Smithy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _373px_Village {
            get {
                object obj = ResourceManager.GetObject("_373px_Village", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _374px_Market {
            get {
                object obj = ResourceManager.GetObject("_374px_Market", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _374px_Militia {
            get {
                object obj = ResourceManager.GetObject("_374px_Militia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _375px_Bazaar {
            get {
                object obj = ResourceManager.GetObject("_375px_Bazaar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _375px_Festival {
            get {
                object obj = ResourceManager.GetObject("_375px_Festival", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _375px_Gold {
            get {
                object obj = ResourceManager.GetObject("_375px_Gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _375px_Province {
            get {
                object obj = ResourceManager.GetObject("_375px_Province", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _375px_Silver {
            get {
                object obj = ResourceManager.GetObject("_375px_Silver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _376px_Woodcutter {
            get {
                object obj = ResourceManager.GetObject("_376px_Woodcutter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;allCards&gt;
        ///	&lt;card&gt;
        ///		&lt;coins&gt;1&lt;/coins&gt;
        ///		&lt;actions&gt;1&lt;/actions&gt;
        ///		&lt;buys&gt;1&lt;/buys&gt;
        ///		&lt;cards&gt;1&lt;/cards&gt;
        ///		&lt;victoryP&gt;0&lt;/victoryP&gt;
        ///		&lt;name&gt;Market&lt;/name&gt;
        ///		&lt;cost&gt;5&lt;/cost&gt;
        ///	&lt;/card&gt;
        ///	&lt;card&gt;
        ///		&lt;coins&gt;2&lt;/coins&gt;
        ///		&lt;actions&gt;2&lt;/actions&gt;
        ///		&lt;buys&gt;1&lt;/buys&gt;
        ///		&lt;cards&gt;0&lt;/cards&gt;
        ///		&lt;victoryP&gt;0&lt;/victoryP&gt;
        ///		&lt;name&gt;Festival&lt;/name&gt;
        ///		&lt;cost&gt;5&lt;/cost&gt;
        ///	&lt;/card&gt;
        ///	&lt;card&gt;
        ///		&lt;coins&gt;0&lt;/coins&gt;
        ///		&lt;actions&gt;2&lt;/actions&gt;
        ///		&lt;buys&gt;0&lt;/buys&gt;
        ///		&lt;cards&gt;1&lt;/cards&gt;
        ///		&lt;victoryP&gt;0&lt;/victoryP&gt;
        ///		&lt;na [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string allCards {
            get {
                return ResourceManager.GetString("allCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;cardRectangles&gt;
        ///	&lt;rectangle&gt;
        ///		&lt;x&gt;19&lt;/x&gt;
        ///		&lt;y&gt;57&lt;/y&gt;
        ///		&lt;width&gt;100&lt;/width&gt;
        ///		&lt;height&gt;125&lt;/height&gt;
        ///		&lt;name&gt;coins1&lt;/name&gt;
        ///	&lt;/rectangle&gt;
        ///	&lt;rectangle&gt;
        ///		&lt;x&gt;19&lt;/x&gt;
        ///		&lt;y&gt;188&lt;/y&gt;
        ///		&lt;width&gt;100&lt;/width&gt;
        ///		&lt;height&gt;125&lt;/height&gt;
        ///		&lt;name&gt;coins2&lt;/name&gt;
        ///	&lt;/rectangle&gt;
        ///	&lt;rectangle&gt;
        ///		&lt;x&gt;19&lt;/x&gt;
        ///		&lt;y&gt;319&lt;/y&gt;
        ///		&lt;width&gt;100&lt;/width&gt;
        ///		&lt;height&gt;125&lt;/height&gt;
        ///		&lt;name&gt;coins3&lt;/name&gt;
        ///	&lt;/rectangle&gt;
        ///	&lt;rectangle&gt;
        ///		&lt;x&gt;125&lt;/x&gt;
        ///		&lt;y&gt;119&lt;/y&gt;
        ///		&lt;width&gt;100&lt;/width&gt;
        ///		&lt;height&gt;125&lt;/h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cardRectangles {
            get {
                return ResourceManager.GetString("cardRectangles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Goons {
            get {
                object obj = ResourceManager.GetObject("Goons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tutImage1 {
            get {
                object obj = ResourceManager.GetObject("tutImage1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tutImage2 {
            get {
                object obj = ResourceManager.GetObject("tutImage2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tutImage3 {
            get {
                object obj = ResourceManager.GetObject("tutImage3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
